import type { Metadata } from "next";
import { Geist_Mono, Gentium_Book_Plus } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Header";
import Footer from "./components/Footer";
import JoinCommunity from "./components/Community";

const gentiumBookPlus = Gentium_Book_Plus({
  variable: "--font-gentium-book-plus",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gentiumBookPlus.className} ${geistMono.variable} antialiased !bg-white`}
      >
        <Navbar />
        {children}
        <JoinCommunity />
        <Footer />
      </body>
    </html>
  );
}
